# Created with package:mono_repo v2.3.0
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: 2.5.0; PKGS: build_equals, build_equals_annotation; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.5.0"
      os: linux
      env: PKGS="build_equals build_equals_annotation"
      script: ./tool/travis.sh dartanalyzer_1
    - stage: analyzer_and_format
      name: "SDK: dev; PKGS: build_equals, build_equals_annotation; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings --fatal-infos .`]"
      dart: dev
      os: linux
      env: PKGS="build_equals build_equals_annotation"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
    - stage: unit_test
      name: "SDK: 2.5.0; PKG: build_equals; TASKS: `pub run test`"
      dart: "2.5.0"
      os: linux
      env: PKGS="build_equals"
      script: ./tool/travis.sh test_0
    - stage: unit_test
      name: "SDK: dev; PKG: build_equals; TASKS: `pub run test`"
      dart: dev
      os: linux
      env: PKGS="build_equals"
      script: ./tool/travis.sh test_0
    - stage: ensure_build
      name: "SDK: 2.5.0; PKG: build_equals; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
      dart: "2.5.0"
      os: linux
      env: PKGS="build_equals"
      script: ./tool/travis.sh test_1
    - stage: ensure_build
      name: "SDK: dev; PKG: build_equals; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
      dart: dev
      os: linux
      env: PKGS="build_equals"
      script: ./tool/travis.sh test_1

stages:
  - analyzer_and_format
  - unit_test
  - ensure_build

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - build_equals/.dart_tool/build
