# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      build_equals:
        generate_for:
          include:
          - example/**
          - test/src/**

builders:
  build_equals:
    import: "package:build_equals/builder.dart"
    builder_factories: ["buildEquals"]
    build_extensions: {".dart": [".build_equals.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
