# See https://pub.dev/packages/mono_repo for details on this file
dart:
- 2.9.3
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.9.3]
- unit_test:
  - test
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart

cache:
  directories:
  - .dart_tool/build
