# See https://pub.dev/packages/mono_repo for details on this file
stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-warnings --fatal-infos .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.9.3]
